In [2]:
import pandas as pd 
df= pd.read_csv(r"C:\Users\RICHA\Desktop\iris.csv")

In [3]:
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
5    4.6  3.4  1.4  0.3     Iris-setosa
6    5.0  3.4  1.5  0.2     Iris-setosa
7    4.4  2.9  1.4  0.2     Iris-setosa
8    4.9  3.1  1.5  0.1     Iris-setosa
9    5.4  3.7  1.5  0.2     Iris-setosa
10   4.8  3.4  1.6  0.2     Iris-setosa
11   4.8  3.0  1.4  0.1     Iris-setosa
12   4.3  3.0  1.1  0.1     Iris-setosa
13   5.8  4.0  1.2  0.2     Iris-setosa
14   5.7  4.4  1.5  0.4     Iris-setosa
15   5.4  3.9  1.3  0.4     Iris-setosa
16   5.1  3.5  1.4  0.3     Iris-setosa
17   5.7  3.8  1.7  0.3     Iris-setosa
18   5.1  3.8  1.5  0.3     Iris-setosa
19   5.4  3.4  1.7  0.2     Iris-setosa
20   5.1  3.7  1.5  0.4     Iris-setosa
21   4.6  3.6  1.0  0.2     Iris-setosa
22   5.1  3.3  1.7  0.5     Iris-setosa
23   4.8  3.4  1.9  0.2     Iris-setosa
24   5.0  3.0  1.6  0.2     Iris-setosa
25   5.0  3.4  1.6  0.4     Iris-setosa
26   5.2  3.5  1.5  0.2     Iris-setosa
27   5.2  3.4  1.4  0.2     Iris-setosa
28   4.7  3.2  1.6  0.2     Iris-setosa
29   4.8  3.1  1.6  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
119  6.9  3.2  5.7  2.3  Iris-virginica
120  5.6  2.8  4.9  2.0  Iris-virginica
121  7.7  2.8  6.7  2.0  Iris-virginica
122  6.3  2.7  4.9  1.8  Iris-virginica
123  6.7  3.3  5.7  2.1  Iris-virginica
124  7.2  3.2  6.0  1.8  Iris-virginica
125  6.2  2.8  4.8  1.8  Iris-virginica
126  6.1  3.0  4.9  1.8  Iris-virginica
127  6.4  2.8  5.6  2.1  Iris-virginica
128  7.2  3.0  5.8  1.6  Iris-virginica
129  7.4  2.8  6.1  1.9  Iris-virginica
130  7.9  3.8  6.4  2.0  Iris-virginica
131  6.4  2.8  5.6  2.2  Iris-virginica
132  6.3  2.8  5.1  1.5  Iris-virginica
133  6.1  2.6  5.6  1.4  Iris-virginica
134  7.7  3.0  6.1  2.3  Iris-virginica
135  6.3  3.4  5.6  2.4  Iris-virginica
136  6.4  3.1  5.5  1.8  Iris-virginica
137  6.0  3.0  4.8  1.8  Iris-virginica
138  6.9  3.1  5.4  2.1  Iris-virginica
139  6.7  3.1  5.6  2.4  Iris-virginica
140  6.9  3.1  5.1  2.3  Iris-virginica
141  5.8  2.7  5.1  1.9  Iris-virginica
142  6.8  3.2  5.9  2.3  Iris-virginica
143  6.7  3.3  5.7  2.5  Iris-virginica
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [4]:
df.shape()

TypeError: 'tuple' object is not callable

In [5]:
df.shape

(149, 5)

In [9]:
df.tail[145 :149]

TypeError: 'method' object is not subscriptable

In [10]:
df.tail[145 :149]

TypeError: 'method' object is not subscriptable

In [11]:
df.[145:149]

SyntaxError: invalid syntax (<ipython-input-11-6ddc0a3289d5>, line 1)

In [12]:
df[145:149]

     5.1  3.5  1.4  0.2     Iris-setosa
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

In [13]:
df.columns

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')

In [14]:
df.3.5

SyntaxError: invalid syntax (<ipython-input-14-f82093fb6b09>, line 1)

In [15]:
df['3.5']

0      3.0
1      3.2
2      3.1
3      3.6
4      3.9
5      3.4
6      3.4
7      2.9
8      3.1
9      3.7
10     3.4
11     3.0
12     3.0
13     4.0
14     4.4
15     3.9
16     3.5
17     3.8
18     3.8
19     3.4
20     3.7
21     3.6
22     3.3
23     3.4
24     3.0
25     3.4
26     3.5
27     3.4
28     3.2
29     3.1
      ...
119    3.2
120    2.8
121    2.8
122    2.7
123    3.3
124    3.2
125    2.8
126    3.0
127    2.8
128    3.0
129    2.8
130    3.8
131    2.8
132    2.8
133    2.6
134    3.0
135    3.4
136    3.1
137    3.0
138    3.1
139    3.1
140    3.1
141    2.7
142    3.2
143    3.3
144    3.0
145    2.5
146    3.0
147    3.4
148    3.0
Name: 3.5, Length: 149, dtype: float64

In [16]:
df[['5.1','3.5']]

     5.1  3.5
0    4.9  3.0
1    4.7  3.2
2    4.6  3.1
3    5.0  3.6
4    5.4  3.9
5    4.6  3.4
6    5.0  3.4
7    4.4  2.9
8    4.9  3.1
9    5.4  3.7
10   4.8  3.4
11   4.8  3.0
12   4.3  3.0
13   5.8  4.0
14   5.7  4.4
15   5.4  3.9
16   5.1  3.5
17   5.7  3.8
18   5.1  3.8
19   5.4  3.4
20   5.1  3.7
21   4.6  3.6
22   5.1  3.3
23   4.8  3.4
24   5.0  3.0
25   5.0  3.4
26   5.2  3.5
27   5.2  3.4
28   4.7  3.2
29   4.8  3.1
..   ...  ...
119  6.9  3.2
120  5.6  2.8
121  7.7  2.8
122  6.3  2.7
123  6.7  3.3
124  7.2  3.2
125  6.2  2.8
126  6.1  3.0
127  6.4  2.8
128  7.2  3.0
129  7.4  2.8
130  7.9  3.8
131  6.4  2.8
132  6.3  2.8
133  6.1  2.6
134  7.7  3.0
135  6.3  3.4
136  6.4  3.1
137  6.0  3.0
138  6.9  3.1
139  6.7  3.1
140  6.9  3.1
141  5.8  2.7
142  6.8  3.2
143  6.7  3.3
144  6.7  3.0
145  6.3  2.5
146  6.5  3.0
147  6.2  3.4
148  5.9  3.0

[149 rows x 2 columns]

In [17]:
df['3.5'].max()

4.4

In [18]:
df['3.5'].mean()

3.051006711409397

In [19]:
df.describe()

              5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [20]:
df[df.'5.1'>= 3]

SyntaxError: invalid syntax (<ipython-input-20-834d45f98b72>, line 1)

In [21]:
df= pd.read_csv(r"C:\Users\RICHA\Desktop\newiris.csv")

In [22]:
df

      a    b    c    d            e
0   5.1  3.5  1.4  0.2  Iris-setosa
1   4.9  3.0  1.4  0.2  Iris-setosa
2   4.7  3.2  1.3  0.2  Iris-setosa
3   4.6  3.1  1.5  0.2  Iris-setosa
4   5.0  3.6  1.4  0.2  Iris-setosa
5   5.4  3.9  1.7  0.4  Iris-setosa
6   4.6  3.4  1.4  0.3  Iris-setosa
7   5.0  3.4  1.5  0.2  Iris-setosa
8   4.4  2.9  1.4  0.2  Iris-setosa
9   4.9  3.1  1.5  0.1  Iris-setosa
10  5.4  3.7  1.5  0.2  Iris-setosa
11  4.8  3.4  1.6  0.2  Iris-setosa
12  4.8  3.0  1.4  0.1  Iris-setosa
13  4.3  3.0  1.1  0.1  Iris-setosa
14  5.8  4.0  1.2  0.2  Iris-setosa
15  5.7  4.4  1.5  0.4  Iris-setosa
16  5.4  3.9  1.3  0.4  Iris-setosa
17  5.1  3.5  1.4  0.3  Iris-setosa
18  5.7  3.8  1.7  0.3  Iris-setosa
19  5.1  3.8  1.5  0.3  Iris-setosa
20  5.4  3.4  1.7  0.2  Iris-setosa
21  5.1  3.7  1.5  0.4  Iris-setosa
22  4.6  3.6  1.0  0.2  Iris-setosa

In [23]:
df[a.maximum()]

NameError: name 'a' is not defined

In [24]:
df[a.max()]

NameError: name 'a' is not defined

In [25]:
df['a']

0     5.1
1     4.9
2     4.7
3     4.6
4     5.0
5     5.4
6     4.6
7     5.0
8     4.4
9     4.9
10    5.4
11    4.8
12    4.8
13    4.3
14    5.8
15    5.7
16    5.4
17    5.1
18    5.7
19    5.1
20    5.4
21    5.1
22    4.6
Name: a, dtype: float64

In [26]:
df['a'].max()

5.8

In [28]:
df[df.a == df.a.max()]

      a    b    c    d            e
14  5.8  4.0  1.2  0.2  Iris-setosa

In [29]:
df[df.a == df.a.max()]

      a    b    c    d            e
14  5.8  4.0  1.2  0.2  Iris-setosa

In [30]:
df[df.a == df.a.max()].b

14    4.0
Name: b, dtype: float64

In [31]:
df.set_index('day')

KeyError: 'day'

In [32]:
df.index

RangeIndex(start=0, stop=23, step=1)

In [33]:
df.set_index('a')

       b    c    d            e
a
5.1  3.5  1.4  0.2  Iris-setosa
4.9  3.0  1.4  0.2  Iris-setosa
4.7  3.2  1.3  0.2  Iris-setosa
4.6  3.1  1.5  0.2  Iris-setosa
5.0  3.6  1.4  0.2  Iris-setosa
5.4  3.9  1.7  0.4  Iris-setosa
4.6  3.4  1.4  0.3  Iris-setosa
5.0  3.4  1.5  0.2  Iris-setosa
4.4  2.9  1.4  0.2  Iris-setosa
4.9  3.1  1.5  0.1  Iris-setosa
5.4  3.7  1.5  0.2  Iris-setosa
4.8  3.4  1.6  0.2  Iris-setosa
4.8  3.0  1.4  0.1  Iris-setosa
4.3  3.0  1.1  0.1  Iris-setosa
5.8  4.0  1.2  0.2  Iris-setosa
5.7  4.4  1.5  0.4  Iris-setosa
5.4  3.9  1.3  0.4  Iris-setosa
5.1  3.5  1.4  0.3  Iris-setosa
5.7  3.8  1.7  0.3  Iris-setosa
5.1  3.8  1.5  0.3  Iris-setosa
5.4  3.4  1.7  0.2  Iris-setosa
5.1  3.7  1.5  0.4  Iris-setosa
4.6  3.6  1.0  0.2  Iris-setosa

In [34]:
df.loc['3.8']

KeyError: 'the label [3.8] is not in the [index]'

In [35]:
df

      a    b    c    d            e
0   5.1  3.5  1.4  0.2  Iris-setosa
1   4.9  3.0  1.4  0.2  Iris-setosa
2   4.7  3.2  1.3  0.2  Iris-setosa
3   4.6  3.1  1.5  0.2  Iris-setosa
4   5.0  3.6  1.4  0.2  Iris-setosa
5   5.4  3.9  1.7  0.4  Iris-setosa
6   4.6  3.4  1.4  0.3  Iris-setosa
7   5.0  3.4  1.5  0.2  Iris-setosa
8   4.4  2.9  1.4  0.2  Iris-setosa
9   4.9  3.1  1.5  0.1  Iris-setosa
10  5.4  3.7  1.5  0.2  Iris-setosa
11  4.8  3.4  1.6  0.2  Iris-setosa
12  4.8  3.0  1.4  0.1  Iris-setosa
13  4.3  3.0  1.1  0.1  Iris-setosa
14  5.8  4.0  1.2  0.2  Iris-setosa
15  5.7  4.4  1.5  0.4  Iris-setosa
16  5.4  3.9  1.3  0.4  Iris-setosa
17  5.1  3.5  1.4  0.3  Iris-setosa
18  5.7  3.8  1.7  0.3  Iris-setosa
19  5.1  3.8  1.5  0.3  Iris-setosa
20  5.4  3.4  1.7  0.2  Iris-setosa
21  5.1  3.7  1.5  0.4  Iris-setosa
22  4.6  3.6  1.0  0.2  Iris-setosa

In [36]:
df.set_index['a', inpace= True]

SyntaxError: invalid syntax (<ipython-input-36-21b9b2e0278b>, line 1)

In [37]:
df.set_index['a', inplace= True]

SyntaxError: invalid syntax (<ipython-input-37-d4f9cf182a70>, line 1)

In [38]:
df.set_index['a', inpace=True]

SyntaxError: invalid syntax (<ipython-input-38-e21c9dedfbdc>, line 1)

In [39]:
df.set_index['a', inplace=True]

SyntaxError: invalid syntax (<ipython-input-39-702fc1b77800>, line 1)

In [40]:
df.set_index('a', inplace= True)

In [41]:
df

       b    c    d            e
a
5.1  3.5  1.4  0.2  Iris-setosa
4.9  3.0  1.4  0.2  Iris-setosa
4.7  3.2  1.3  0.2  Iris-setosa
4.6  3.1  1.5  0.2  Iris-setosa
5.0  3.6  1.4  0.2  Iris-setosa
5.4  3.9  1.7  0.4  Iris-setosa
4.6  3.4  1.4  0.3  Iris-setosa
5.0  3.4  1.5  0.2  Iris-setosa
4.4  2.9  1.4  0.2  Iris-setosa
4.9  3.1  1.5  0.1  Iris-setosa
5.4  3.7  1.5  0.2  Iris-setosa
4.8  3.4  1.6  0.2  Iris-setosa
4.8  3.0  1.4  0.1  Iris-setosa
4.3  3.0  1.1  0.1  Iris-setosa
5.8  4.0  1.2  0.2  Iris-setosa
5.7  4.4  1.5  0.4  Iris-setosa
5.4  3.9  1.3  0.4  Iris-setosa
5.1  3.5  1.4  0.3  Iris-setosa
5.7  3.8  1.7  0.3  Iris-setosa
5.1  3.8  1.5  0.3  Iris-setosa
5.4  3.4  1.7  0.2  Iris-setosa
5.1  3.7  1.5  0.4  Iris-setosa
4.6  3.6  1.0  0.2  Iris-setosa

In [42]:
df.loc[3.8]

KeyError: 'the label [3.8] is not in the [index]'

In [43]:
df.loc['3.8']

KeyError: 'the label [3.8] is not in the [index]'

In [44]:
df.loc[5.4]

       b    c    d            e
a
5.4  3.9  1.7  0.4  Iris-setosa
5.4  3.7  1.5  0.2  Iris-setosa
5.4  3.9  1.3  0.4  Iris-setosa
5.4  3.4  1.7  0.2  Iris-setosa

In [45]:
df.reset_index(inplace= True)

In [46]:
df

      a    b    c    d            e
0   5.1  3.5  1.4  0.2  Iris-setosa
1   4.9  3.0  1.4  0.2  Iris-setosa
2   4.7  3.2  1.3  0.2  Iris-setosa
3   4.6  3.1  1.5  0.2  Iris-setosa
4   5.0  3.6  1.4  0.2  Iris-setosa
5   5.4  3.9  1.7  0.4  Iris-setosa
6   4.6  3.4  1.4  0.3  Iris-setosa
7   5.0  3.4  1.5  0.2  Iris-setosa
8   4.4  2.9  1.4  0.2  Iris-setosa
9   4.9  3.1  1.5  0.1  Iris-setosa
10  5.4  3.7  1.5  0.2  Iris-setosa
11  4.8  3.4  1.6  0.2  Iris-setosa
12  4.8  3.0  1.4  0.1  Iris-setosa
13  4.3  3.0  1.1  0.1  Iris-setosa
14  5.8  4.0  1.2  0.2  Iris-setosa
15  5.7  4.4  1.5  0.4  Iris-setosa
16  5.4  3.9  1.3  0.4  Iris-setosa
17  5.1  3.5  1.4  0.3  Iris-setosa
18  5.7  3.8  1.7  0.3  Iris-setosa
19  5.1  3.8  1.5  0.3  Iris-setosa
20  5.4  3.4  1.7  0.2  Iris-setosa
21  5.1  3.7  1.5  0.4  Iris-setosa
22  4.6  3.6  1.0  0.2  Iris-setosa